[package]
name = "mud"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_ratatui = { version = "0.9.2", default-features = true, features = [
    "windowed",
] }
ratatui = "0.29.0"
